DEBUG : False  # if true : model saving, logging turned off.  
INIT_VAL : True
GREEDY_BASELINE : True
SAVE_BEST_METRIC : True # to save nothing : = False and checkpoint_freq = 0
ONLY_INFERENCE : False
ONLY_VAL : False
  
captions_type : "coco" #coco, (mistral, mistral_4), blip_holistic
train_method : "cider" # (discriminative, cider, mle)
prefix_len : 10
warmup_ratio : 0.034
official_clipcap_weights : /home/manugaur/official_clipcap/coco_weights.pt
num_workers : 16
CAPS_PER_IMG_train: 4
CAPS_PER_IMG_val: 4

lora : False
lora_rank : 32

neg_mining:
  do : False
  bag_size : 10  
  val : False

opts: 
  baseline : mean
  n_epochs : 20
  batch_size : 180
  lr : 1e-7 #2e-5
  max_len : 50
  checkpoint_freq : 0
  num_workers : 16
  dataset_dir : /home/manugaur/coco
  mle_model_path : /home/manugaur/EGG/checkpoints/blip2mistral/mle/best.pt # mistral_4 , coco
  checkpoint_dir : /home/manugaur/EGG/checkpoints/blip2mistral/sr
    
WANDB :
  logging : True
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "emergent_captioner"
  run_name : g_baseline #suffix to "sr_{data}_"

inference : 
  batch_size : 100
  output_dir : /home/manugaur/EGG/inference_preds/

#DEBUG, ONLY_INFERENCE,  INIT_VAL, logging, batch_size, n_epochs
#CKPT_DIR = f"{method}/{data}_{config[WANDB][run_name]}