DEBUG : False  # if true : model saving, logging turned off.  
INIT_VAL : True
GREEDY_BASELINE : False
SAVE_BEST_METRIC : True # to save nothing : = False and checkpoint_freq = 0
ONLY_INFERENCE : True
SAVE_PREDS :  True
ONLY_VAL : False

CIDER_SR : False
dataset : "coco"
captions_type : "coco" #coco, (mistral, mistral_4), blip_holistic
train_method : "discriminative" # (discriminative, cider, mle)
prefix_len : 10
warmup_ratio : 0.034
official_clipcap_weights : /home/manugaur/official_clipcap/coco_weights.pt
num_workers : 16
CAPS_PER_IMG_train: 5 # maybe use in CL
CAPS_PER_IMG_val: 5 # NLG eval
fp16: False
diff_lr: False
contrastive : False
reinforce : True
mllm : "clipcap"

#lora
lora : True
finetune_model : clip # {llm, clip, both} # automatically freeze gpt.transformer or CLIP
lora_rank : 32
clip_mlp_ft : True
adapter_lora : False
adapter_rank : 32
clip_text : False

# freezing layers
freeze_wte : True
freeze_adapter : False
log_spice : False

neg_mining:
  curricullum : {20 : ["rand",5]}  #{3 : ["hard", 2] , 8 : ["hard",3], 10 : ["hard",5], 12 : ["hard",7], 14 : ["hard",10], 17 : ["hard",15], 20 : ["hard",20]} 
  save_optimizer : True
  save_using_neg : False #save model i.e best on neg_dataloader 
  val_bag_size : 5
  val_level : "rand"

resume_training : 
  do : False
  dir : sr_easy_bsz5
  load_epoch  : 2 

opts: 
  baseline : mean
  batch_size : 100
  lr : 9e-8 #2e-5
  max_len : 50
  checkpoint_freq : 0
  num_workers : 16
  dataset_dir : /home/manugaur/coco
  mle_model_path : /home/manugaur/EGG/checkpoints/blip2mistral/mle/best.pt #it loads only sender.clipcap (adapter + llm)
  checkpoint_dir : /home/manugaur/EGG/checkpoints/blip2mistral/sr
  recv_clip_model : ViT-B/32 #ViT-L/14@336px

WANDB:
  logging : True
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "emergent_captioner"
  run_name : clip_final
  log_mmvp_all : False

inference : 
  batch_size : 100
  output_dir : /home/manugaur/EGG/inference_preds/

#DEBUG, INIT_VAL | ONLY_INFERENCE,  , logging, save_using_neg
#CKPT_DIR = f"{data}/{sr}_{config[WANDB][run_name]}

#CIDER_SR : GREEDY_BASELINE = False 

