DEBUG : False  # if true : model saving, logging turned off.  
INIT_VAL : True
GREEDY_BASELINE : False
SAVE_BEST_METRIC : True # to save nothing : = False and checkpoint_freq = 0
ONLY_INFERENCE : False
ONLY_VAL : False

captions_type : "coco" #coco, (mistral, mistral_4), blip_holistic
train_method : "discriminative" # (discriminative, cider, mle)
prefix_len : 10
warmup_ratio : 0.034
official_clipcap_weights : /home/manugaur/official_clipcap/coco_weights.pt
num_workers : 8
CAPS_PER_IMG_train: 1 # maybe use in CL
CAPS_PER_IMG_val: 4 # NLG eval
fp16: False
diff_lr: False
contrastive : False
reinforce : True
mllm : "llava-phi" # {llava, clipcap}

#lora
# lora : False

# clip_mlp_ft: True
# clip_text : True

#hparams:
temp : 0.4
max_new_tokens : 50
lora_rank : 8
iters_per_eval : 360 # eval every 30 mins
log_spice : False
n_layers : 5
lm_head : False

finetune_model : llm # {gpt, clip} # automatically freeze gpt.transformer or CLIP
freeze_wte : False
freeze_adapter : False

neg_mining:
  curricullum : {"medium" : 10} # "easy" : 3, "medium": 7, "hard" : 20} #indexed from 1 {"medium" : 3, "hard" : 10}
  bag_size : 2
  save_using_neg : False #save model i.e best on neg_dataloader 
  val_bag_size : 5
  val_level : "medium"

opts: 
  baseline : mean
  n_epochs : 10
  batch_size : 26
  lr : 1e-8 #2e-5
  max_len : 50
  checkpoint_freq : 0
  num_workers : 8
  dataset_dir : /home/manugaur/coco
  # mle_model_path : /home/manugaur/EGG/checkpoints/blip2mistral/mle/best.pt #it loads only sender.clipcap (adapter + llm)
  checkpoint_dir : /home/manugaur/EGG/checkpoints/blip2mistral/sr
  recv_clip_model : ViT-L/14@336px #ViT-B/32
WANDB:
  logging : True
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "emergent_captioner"
  run_name :  llava_5layers_t0.4_M10_bsz2_lr1e8_valMedium #suffix to "sr_{data}_"
  log_mmvp_all : True

inference : 
  batch_size : 128
  output_dir : /home/manugaur/EGG/inference_preds/

#DEBUG, ONLY_INFERENCE,  INIT_VAL, logging, save_using_neg
#CKPT_DIR = f"{data}/{sr}_{config[WANDB][run_name]}
